import { Resend } from 'resend';
import { NextResponse } from 'next/server';
import { jsPDF } from "jspdf";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { email, name, phone, school, board, batch, trxId, ticketId, status, reason } = body;

    if (status === 'approved') {
      const doc = new jsPDF({
        orientation: "landscape",
        unit: "px",
        format: [600, 400]
      });

      // ১. টিকেট ডিজাইন (Black Background)
      doc.setFillColor(0, 0, 0);
      doc.rect(0, 0, 600, 400, 'F');

      // ২. লোগো সেকশন (PNG URL ব্যবহার করে)
      try {
        // এখানে তোমার লোগোর সরাসরি লিং বসাও (যেমন: তোমার পোর্টফোলিও সাইটে হোস্ট করা ইমেজ)
        const relaxLogo = "https://syedfahimmuddasir.bro.bd/relax-logo.png"; 
        const b24Logo = "https://syedfahimmuddasir.bro.bd/b24-logo.png";
        
        // ইমেজ লোড হতে সমস্যা হলে যেন কোড ক্র্যাশ না করে তাই try-catch এ রাখা
        // doc.addImage(relaxLogo, 'PNG', 20, 20, 40, 40);
        // doc.addImage(b24Logo, 'PNG', 70, 20, 40, 40);
      } catch (imgError) {
        console.error("Logo failed to load, skipping images.");
      }

      // ৩. স্কুইড গেম আইকন (Pink)
      doc.setTextColor(255, 0, 90); 
      doc.setFontSize(35);
      doc.text("○  △  □", 460, 50);

      doc.setDrawColor(255, 0, 90);
      doc.line(20, 75, 580, 75);
      
      doc.setFontSize(22);
      doc.setTextColor(255, 255, 255);
      doc.text("PARTICIPANT DOSSIER", 20, 105);

      // ৪. এ টু জেড ইনফরমেশন
      doc.setFontSize(12);
      const startY = 145;
      const lineHeight = 25;

      const details = [
        { label: "NAME", value: String(name || 'N/A').toUpperCase() },
        { label: "PHONE", value: String(phone || 'N/A') },
        { label: "INSTITUTION", value: String(school || 'WLFSC').toUpperCase() },
        { label: "BOARD", value: String(board || 'DHAKA') },
        { label: "SSC BATCH", value: String(batch || '2024') },
        { label: "TRANSACTION ID", value: String(trxId || 'N/A').toUpperCase() },
        { label: "TICKET ID", value: `#${ticketId}` }
      ];

      details.forEach((item, index) => {
        doc.setTextColor(255, 0, 90);
        doc.text(`${item.label}:`, 20, startY + (index * lineHeight));
        doc.setTextColor(255, 255, 255);
        doc.text(item.value, 150, startY + (index * lineHeight));
      });

      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text("SECURITY PROTOCOL: GENERATED BY RELAXSTUDIO. DO NOT DUPLICATE.", 20, 380);

      // ৫. পিডিএফ বাফার তৈরি
      const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

      // ৬. ইমেইল পাঠানো (এপ্রুভড)
      await resend.emails.send({
        from: 'B24 Reunion <onboarding@backbenchers24.pro.bd>', // টেস্টের জন্য এটা ফিক্সড রাখো
        to: email,
        subject: `Your Player Invitation: #${ticketId}`,
        html: `<p>Greetings <b>${name}</b>, your payment for BackBencher's 24 Mega-Reunion is verified. Find your dossier attached.</p>`,
        attachments: [{ filename: `B24_Ticket_${ticketId}.pdf`, content: pdfBuffer }]
      });

      return NextResponse.json({ success: true });
    } 
    
    else if (status === 'rejected') {
      await resend.emails.send({
        from: 'B24 Support <info@backbenchers24.pro.bd>',
        to: email,
        subject: 'Registration Status Update',
        html: `<div style="font-family: sans-serif; border: 1px solid #ff005a; padding: 20px; border-radius: 10px;">
                <h2 style="color: #ff005a;">Registration Rejected</h2>
                <p>Dear ${name}, your registration couldn't be verified. <b>Reason:</b> ${reason}</p>
              </div>`
      });
      return NextResponse.json({ success: true });
    }

    return NextResponse.json({ error: "Invalid status" }, { status: 400 });

  } catch (error: any) {
    console.error("Critical API Error:", error.message);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
