import { Resend } from 'resend';
import { NextResponse } from 'next/server';
import { jsPDF } from "jspdf";



const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { email, name, phone, school, board, batch, trxId, ticketId, status, reason } = body;

    // পেমেন্ট অ্যাপ্রুভ হলে টিকেট পাঠানো
    if (status === 'approved') {
      const doc = new jsPDF({
        orientation: "landscape",
        unit: "px",
        format: [600, 400]
      });

      // ১. টিকেট ডিজাইন (Squid Game Aesthetic)
      doc.setFillColor(0, 0, 0);
      doc.rect(0, 0, 600, 400, 'F');

      doc.setTextColor(255, 0, 90); // Pink (#FF005A)
      doc.setFontSize(35);
      doc.text("○  △  □", 460, 50);

      doc.setDrawColor(255, 0, 90);
      doc.line(20, 75, 580, 75);
      
      doc.setFontSize(22);
      doc.setTextColor(255, 255, 255);
      doc.text("PARTICIPANT DOSSIER", 20, 105);

      // ২. ইনফরমেশন লিস্ট
      doc.setFontSize(12);
      const startY = 145;
      const lineHeight = 25;

      const details = [
        { label: "NAME", value: String(name).toUpperCase() },
        { label: "PHONE", value: String(phone) },
        { label: "INSTITUTION", value: String(school).toUpperCase() },
        { label: "BOARD", value: String(board) },
        { label: "SSC BATCH", value: String(batch) },
        { label: "TRANSACTION ID", value: String(trxId).toUpperCase() },
        { label: "TICKET ID", value: `#${ticketId}` }
      ];

      details.forEach((item, index) => {
        doc.setTextColor(255, 0, 90);
        doc.text(`${item.label}:`, 20, startY + (index * lineHeight));
        doc.setTextColor(255, 255, 255);
        doc.text(item.value, 150, startY + (index * lineHeight));
      });

      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text("SECURITY PROTOCOL: GENERATED BY RELAXSTUDIO. DO NOT DUPLICATE.", 20, 380);

      const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

      await resend.emails.send({
        from: 'B24 Reunion <tickets@backbenchers24.pro.bd>',
        to: email,
        subject: `Your Player Invitation: #${ticketId}`,
        html: `<p>Greetings <b>${name}</b>, your payment for BackBencher's 24 Mega-Reunion is verified. Find your dossier attached.</p>`,
        attachments: [{ filename: `B24_Ticket_${ticketId}.pdf`, content: pdfBuffer }]
      });

      return NextResponse.json({ success: true });
    } 
    
    // পেমেন্ট রিজেক্ট হলে নোটিফিকেশন পাঠানো
    else if (status === 'rejected') {
      await resend.emails.send({
        from: 'B24 Support <support@backbenchers24.pro.bd>',
        to: email,
        subject: 'Registration Status Update',
        html: `
          <div style="font-family: sans-serif; border: 1px solid #ff005a; padding: 20px; border-radius: 10px;">
            <h2 style="color: #ff005a;">Registration Rejected</h2>
            <p>Dear ${name}, your registration couldn't be verified.</p>
            <p><b>Reason:</b> ${reason}</p>
            <p>If this was a mistake, please contact support with your payment proof.</p>
          </div>
        `
      });
      return NextResponse.json({ success: true });
    }

    return NextResponse.json({ error: "Invalid status" }, { status: 400 });

  } catch (error: any) {
    console.error(error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
